#!/usr/bin/python
# #####################################################################################
from os import system as SYS;

# #####################################################################################
PACKAGES = [

    "libmono-addins-gui0.2-cil",
    "libmono-system-reactive-debugger2.2-cil",
    "libmono-system-reactive-runtime-remoting2.2-cil",
    "libmono-compilerservices-symbolwriter4.0-cil",
    "libmono-system-data4.0-cil",
    "libmono-system-servicemodel4.0a-cil",
    "libmono-system-runtime-caching4.0-cil",
    "libmono-system-ldap4.0-cil",
    "libmono-system-design4.0-cil",
    "libmono-system-reactive-experimental2.2-cil",
    "libmono-microsoft-csharp4.0-cil",
    "libmono-i18n-cjk4.0-cil",
    "libmonoboehm-2.0-dev",
    "libmono-system-data-datasetextensions4.0-cil",
    "libmono-system-xml4.0-cil",
    "libmono-system-servicemodel-discovery4.0-cil",
    "libmono-system-net-http-formatting4.0-cil",
    "libmono-corlib4.5-cil",
    "libmono-rabbitmq4.0-cil",
    "libmono-system-web-extensions4.0-cil",
    "libmono-system-servicemodel-activation4.0-cil",
    "libmono-simd4.0-cil",
    "libmono-system-xml-serialization4.0-cil",
    "libmono-system-web-routing4.0-cil",
    "libmono-system-serviceprocess4.0-cil",
    "libmono-system-componentmodel-composition4.0-cil",
    "libmono-c5-1.1-cil",
    "libmono-system-runtime4.0-cil",
    "libmono-relaxng4.0-cil",
    "libmono-csharp4.0c-cil",
    "libmono-xbuild-tasks4.0-cil",
    "libmono-system-web-http-selfhost4.0-cil",
    "libmono-sharpzip4.84-cil",
    "libmono-microsoft-build-framework4.0-cil",
    "libmono-microsoft-build-tasks-v4.0-4.0-cil",
    "libmono-system-reactive-providers2.2-cil",
    "libmono-system-reactive-windows-threading2.2-cil",
    "libmono-system-json-microsoft4.0-cil",
    "libmono-messaging-rabbitmq4.0-cil",
    "libmono-system-reactive-windows-forms2.2-cil",
    "libmono-system-web-services4.0-cil",
    "libmono-microsoft-build-utilities-v4.0-4.0-cil",
    "libmono-http4.0-cil",
    "libmono-system-windows4.0-cil",
    "libmono-cairo4.0-cil",
    "libmono-microsoft-visualc10.0-cil",
    "libmono-system-web-dynamicdata4.0-cil",
    "libmonogame-cil",
    "libmono-i18n-mideast4.0-cil",
    "libmono-oracle4.0-cil",
    "libmono-system-configuration4.0-cil",
    "libmono-system-servicemodel-web4.0-cil",
    "libmono-system-net-http-webrequest4.0-cil",
    "libmono-2.0-dev",
    "libmono-messaging4.0-cil",
    "libmono-i18n-west4.0-cil",
    "libmono-system-web-mvc3.0-cil",
    "libmono-system-messaging4.0-cil",
    "libmono-posix4.0-cil",
    "libmono-microsoft-web-infrastructure1.0-cil",
    "libmono-system-data-entity4.0-cil",
    "libmono-security4.0-cil",
    "libmono-system-windows-forms4.0-cil",
    "libmono-system-data-services4.0-cil",
    "libmono-microsoft-build4.0-cil",
    "libmonoboehm-2.0-1",
    "libmono-system-identitymodel4.0-cil",
    "libmono-system-numerics4.0-cil",
    "libmono-cscompmgd0.0-cil",
    "libmono-system-web-applicationservices4.0-cil",
    "libmono-addins0.2-cil",
    "libmono-system-servicemodel-routing4.0-cil",
    "libmono-system-componentmodel-dataannotations4.0-cil",
    "libmono-cil-dev",
    "libmono-system-reactive-core2.2-cil",
    "libmono-system-data-services-client4.0-cil",
    "libmono-system-data-linq4.0-cil",
    "libmonosgen-2.0-1",
    "libmono-sqlite4.0-cil",
    "libmono-system-web4.0-cil",
    "libmono-system-drawing4.0-cil",
    "libmono-system-runtime-serialization-formatters-soap4.0-cil",
    "libmono-system-web-razor2.0-cil",
    "libmono-system-security4.0-cil",
    "libmono-corlib4.0-cil",
    "libmonogame-cil-dev",
    "libmono-tasklets4.0-cil",
    "libmono-system-threading-tasks-dataflow4.0-cil",
    "libmono-system-drawing-design4.0-cil",
    "libmono-parallel4.0-cil",
    "libmono-system-io-compression-filesystem4.0-cil",
    "libmono-codecontracts4.0-cil",
    "libmono-system-runtime-serialization4.0-cil",
    "libmono-ldap4.0-cil",
    "libmono-peapi4.0a-cil",
    "libmono-system-reactive-platformservices2.2-cil",
    "libmono-2.0-1",
    "libmono-accessibility4.0-cil",
    "libmono-db2-1.0-cil",
    "libmono-cecil-private-cil",
    "libmono-windowsbase4.0-cil",
    "libmono-i18n-rare4.0-cil",
    "libmono-i18n-other4.0-cil",
    "libmono-system-web-http-webhost4.0-cil",
    "libmono-system-web-abstractions4.0-cil",
    "libmono-system-web-extensions-design4.0-cil",
    "libmono-system-web-webpages2.0-cil",
    "libmono-system-web-http4.0-cil",
    "libmono-system-reactive-interfaces2.2-cil",
    "libmono-system-web-webpages-deployment2.0-cil",
    "libmono-system-transactions4.0-cil",
    "libmono-profiler",
    "libmono-system-json4.0-cil",
    "libmono-management4.0-cil",
    "libmono-debugger-soft4.0a-cil",
    "libmono-system-xml-linq4.0-cil",
    "libmono-system-windows-forms-datavisualization4.0a-cil",
    "libmono-system-ldap-protocols4.0-cil",
    "libmono-webbrowser4.0-cil",
    "libmono-system-reactive-linq2.2-cil",
    "libmono-system4.0-cil",
    "libmono-system-configuration-install4.0-cil",
    "libmono-custommarshalers4.0-cil",
    "libmono-system-net-http4.0-cil",
    "libmono-system-core4.0-cil",
    "libmono-system-web-webpages-razor2.0-cil",
    "libmono-system-enterpriseservices4.0-cil",
    "libmono-system-xaml4.0-cil",
    "libmono-system-reactive-observable-aliases0.0-cil",
    "libmono-system-dynamic4.0-cil",
    "libmono-system-runtime-durableinstancing4.0-cil",
    "libmono-system-io-compression4.0-cil",
    "libmono-microsoft-build-engine4.0-cil",
    "libmono-webmatrix-data4.0-cil",
    "libmono-system-identitymodel-selectors4.0-cil",
    "libmono-system-management4.0-cil",
    "libmono-system-net4.0-cil",
    "libmono-i18n4.0-all",
    "libmono-data-tds4.0-cil",
    "libmono-i18n4.0-cil",
    "libmono-upnp-cil-dev",
    "libmono-debugger-soft4.0-cil",
    "libmono-facades-system-io-cil",
    "libmono-facades-system-net-networkinformation-cil",
    "libmono-web4.0-cil",
    "libmono-microsoft-visualbasic11.0-cil",
    "libmono-upnp-cil",
    "libmono2.0-cil",
    "libmono-system-net2.0-cil",
    "libmono-system-servicemodel4.0-cil",
    "libmono-data-tds2.0-cil",
    "libmono-i18n2.0-cil",
    "libmono-reflection-cil",
    "libmono-cscompmgd8.0-cil",
    "libmono0",
    "libmono-system-data2.0-cil",
    "libmono-cecil-cil",
    "libmono-uia3.0-cil",
    "libmono-peapi2.0a-cil",
    "libmono-system-ldap2.0-cil",
    "libmono-debugger-soft2.0-cil",
    "libmono-peapi4.0-cil",
    "libmono-facades-system-reflection-primitives-cil",
    "libmono-facades-system-linq-parallel-cil",
    "libmono-nunit2.2-cil",
    "libmono-facades-system-reflection-extensions-cil",
    "libmono-entityframework-sqlserver6.0-cil",
    "libmono-facades-system-objectmodel-cil",
    "libmono-facades-system-text-encoding-cil",
    "libmono-cecil-vb0.9-cil",
    "libmono-rabbitmq2.0-cil",
    "libmono-system-servicemodel-internals0.0-cil",
    "libmono-system-reactive-core2.1-cil",
    "libmono-debugger-soft0.0-cil",
    "libmono-addins-gui-cil-dev",
    "libmono-facades-system-collections-concurrent-cil",
    "libmono-peapi2.0-cil",
    "libmono-zeroconf1.0-cil",
    "libmono-cecil0.4-cil",
    "libmono-simd2.0-cil",
    "libmono-windowsbase3.0-cil",
    "libmono-smdiagnostics0.0-cil",
    "libmono-debugger-soft2.0a-cil",
    "libmono-uia-atkbridge1.0-cil",
    "libmono-facades-system-runtime-serialization-json-cil",
    "libmono-facades-system-threading-tasks-cil",
    "libmono-csharp4.0-cil",
    "libmono-system-runtime2.0-cil",
    "libmono-relaxng2.0-cil",
    "libmono-uia-cil-dev",
    "libmono-facades-system-runtime-interopservices-cil",
    "libmono-facades-system-servicemodel-http-cil",
    "libmono-xbuild-tasks2.0-cil",
    "libmono-microsoft-visualbasic8.0-cil",
    "libmono-addins-msbuild0.2-cil",
    "libmono-addins-cil-dev",
    "libmono-facades-system-security-principal-cil",
    "libmono-facades-system-runtime-serialization-primitives-cil",
    "libmono-messaging-rabbitmq2.0-cil",
    "libmono-cecil-cil-dev",
    "libmono-system-reactive-platformservices2.1-cil",
    "libmono-cairo2.0-cil",
    "libmono-fuse-cil",
    "libmono-facades-system-dynamic-runtime-cil",
    "libmono-zeroconf-cil-dev",
    "libmono-sharpzip2.6-cil",
    "libmono-oracle2.0-cil",
    "libmono-npgsql4.0-cil",
    "libmono-facades-system-linq-expressions-cil",
    "libmono-messaging2.0-cil",
    "libmono-i18n-west2.0-cil",
    "libmono-system-reactive-interfaces2.1-cil",
    "libmono-uia-winforms1.0-cil",
    "libmono-system-web-mvc1.0-cil",
    "libmono-system-messaging2.0-cil",
    "libmono-posix2.0-cil",
    "libmono-winforms2.0-cil",
    "libmono-microsoft8.0-cil",
    "libmono-security2.0-cil",
    "libmono-system-data-services2.0-cil",
    "libmono-microsoft-build2.0-cil",
    "libmono-facades-system-runtime-extensions-cil",
    "libmono-cecil0.5-cil",
    "libmono-webbrowser0.5-cil",
    "libmono-npgsql2.0-cil",
    "libmono-facades-system-diagnostics-contracts-cil",
    "libmono-system-reactive-linq2.1-cil",
    "libmono-facades-system-xml-xdocument-cil",
    "libmono-facades-system-reflection-cil",
    "libmono-facades-system-xml-xmlserializer-cil",
    "libmono-facades-system-collections-cil",
    "libmono-facades-system-diagnostics-tools-cil",
    "libmono-microsoft-visualbasic10.0-cil",
    "libmono1.0-cil",
    "libmono-csharp4.0a-cil",
    "libmono-system-data-linq2.0-cil",
    "libmono-facades-system-threading-tasks-parallel-cil",
    "libmono-sqlite2.0-cil",
    "libmono-reflection-cil-dev",
    "libmono-facades-system-runtime-serialization-xml-cil",
    "libmono-facades-system-xml-readerwriter-cil",
    "libmono-system-web2.0-cil",
    "libmono-facades-system-linq-cil",
    "libmono-opensystem-c4.0-cil",
    "libmono-cecil-flowanalysis-cil",
    "libmono-sharpzip2.84-cil",
    "libmono-corlib2.0-cil",
    "libmono-facades-system-net-primitives-cil",
    "libmono-tasklets2.0-cil",
    "libmono-facades-system-text-regularexpressions-cil",
    "libmono-system-reactive-debugger2.1-cil",
    "libmono-system-reactive-runtime-remoting2.1-cil",
    "libmono-dev",
    "libmono-cecil-flowanalysis0.1a-cil",
    "libmono-nunit2.4-cil",
    "libmono-wcf3.0a-cil",
    "libmono-ldap2.0-cil",
    "libmono-system-reactive-experimental2.1-cil",
    "libmono-facades-system-globalization-cil",
    "libmono-accessibility2.0-cil",
    "libmono-cecil-flowanalysis-cil-dev",
    "libmono-facades-system-componentmodel-annotations-cil",
    "libmono-facades-system-runtime-numerics-cil",
    "libmono-cecil-flowanalysis0.1-cil",
    "libmonosgen-2.0-1-dbg",
    "libmonosgen-2.0-dev",
    "libmono-facades-system-servicemodel-primitives-cil",
    "libmono-2.0-1-dbg",
    "libmono-facades-system-net-requests-cil",
    "libmonoboehm-2.0-1-dbg",
    "libmono-system-json2.0-cil",
    "libmono-management2.0-cil",
    "libmono-c5-1.0-cil",
    "libmono-csharp4.0b-cil",
    "libmono-facades-system-runtime-cil",
    "libmono-entityframework6.0-cil",
    "libmono-system-windows-forms-datavisualization4.0-cil",
    "libmono-facades-system-diagnostics-debug-cil",
    "libmono-cairo1.0-cil",
    "libmono-cecil0.3-cil",
    "libmono-facades-system-resources-resourcemanager-cil",
    "libmono-facades-system-text-encoding-extensions-cil",
    "libmono-system-web-mvc2.0-cil",
    "libmono-wcf3.0-cil",
    "libmono-webbrowser2.0-cil",
    "libmono-system-reactive-providers2.1-cil",
    "libmono-system-reactive-windows-threading2.1-cil",
    "libmono-facades-system-componentmodel-eventbasedasync-cil",
    "libmono-system2.0-cil",
    "libmono-system-reactive-windows-forms2.1-cil",
    "libmono-facades-system-componentmodel-cil",
    "libmono-facades-system-linq-queryable-cil",
    "libmono-facades-system-threading-cil",
    "libmono-addins-msbuild-cil-dev"
];

# #####################################################################################

class Exclude(object):

    # =============================================================
    def __init__(self, _PACKAGES):

        self.CMD                = "sudo apt-mark unhold [PACKAGE]";
        self.PACKAGES           = _PACKAGES;
        self.C                  = 0;
        self.TTL                = str(len(self.PACKAGES));


        self.EXCLUDE();


    # =============================================================
    def EXCLUDE(self):

        for package in self.PACKAGES:

            print("=================================================================")
            print("["+str(self.C)+" of "+self.TTL+"] : Excluding: "+str(package))
            SYS( self.CMD.replace( "[package]", package ) );
            self.C += 1;


    # =============================================================

# #####################################################################################
if __name__ == '__main__':
    
    _Exclude = Exclude( PACKAGES );

